name: Sync
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api /repos/openapi-kr/sdks/dispatches -f event_type='sync_specifications'
          gh api /repos/openapi-kr/openapi-kr.github.io/dispatches -f event_type='sync_specifications'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
